### ISSUE TITLE
Telemetry data couldn't be sent, but the command ran successfully. [WARNING]: <urlopen error [Errno -2] Name or service not known> Execution status: FAIL

### ISSUE THREAD

**Issue by imenselmi** [NVIDIA-AI-IOT/nvidia-tao#7]
i ran this command to convert coco dataset to tfrecords using nvidia tao : 

sudo docker run -it --rm --gpus all -v /home/mj/TAO/workspace:/workspace nvcr.io/nvidia/tao/tao-toolkit:4.0.1-tf1.15.5  mask_rcnn dataset_convert  -i /home/mj/TAO/getting_started_v4.0.1/notebooks/tao_launcher_starter_kit/mask_rcnn/data/raw-data/val2017 -a /home/mj/TAO/getting_started_v4.0.1/notebooks/tao_launcher_starter_kit/mask_rcnn/data/raw-data/annotations/instances_val2017.json  -o /home/mj/TAO/getting_started_v4.0.1/notebooks/tao_launcher_starter_kit/mask_rcnn/data --include_masks -t val -s 32 

the path is correct and the data exist but it return that data path doesn't exist !! how can i solve this problem ? 

the error : 

==============================
=== TAO Toolkit TensorFlow ===
==============================

NVIDIA Release 4.0.1-TensorFlow (build )
TAO Toolkit Version 4.0.1

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the TAO Toolkit End User License Agreement.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/tao-toolkit-software-license-agreement

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for TAO Toolkit.  NVIDIA recommends the use of the following flags:
   docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 ...

Using TensorFlow backend.
2023-05-24 08:41:56.258242: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
/usr/local/lib/python3.6/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
2023-05-24 08:41:59.420131: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2023-05-24 08:41:59.850968: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libnvinfer.so.8
2023-05-24 08:41:59.865294: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
/usr/local/lib/python3.6/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Using TensorFlow backend.
Traceback (most recent call last):
  File "</usr/local/lib/python3.6/dist-packages/iva/mask_rcnn/scripts/dataset_convert.py>", line 3, in <module>
  File "<frozen iva.mask_rcnn.scripts.dataset_convert>", line 415, in <module>
  File "<frozen iva.mask_rcnn.scripts.dataset_convert>", line 403, in <module>
  File "<frozen iva.mask_rcnn.scripts.dataset_convert>", line 292, in main
FileNotFoundError: [Errno 2] No such file or directory: '/home/mj/TAO/getting_started_v4.0.1/notebooks/tao_launcher_starter_kit/mask_rcnn/data'
Telemetry data couldn't be sent, but the command ran successfully.
[WARNING]: <urlopen error [Errno -2] Name or service not known>
Execution status: FAIL

**Comment by ramanathan831** [comment]
run it an interactive docker mode, you'll find the path issue.
You are attaching the volume to /workspace/ but your command still refers to host machine path.
Also, this is not a issue for this repo, you can reopen it in the tao-toolkit forum here: https://forums.developer.nvidia.com/c/accelerated-computing/intelligent-video-analytics/tao-toolkit/17
